services:
  - type: worker
    name: pyrogram-bot-render
    envVars:
      - key: API_ID
        value: ${API_ID}
      - key: API_HASH
        value: ${API_HASH}
      - key: BOT_TOKEN
        value: ${BOT_TOKEN}
    buildCommand: pip install -r requirements.txt
    startCommand: python src/newfile.py
